### ISSUE TITLE
Visibility issue in Light theme

### ISSUE THREAD

**Issue by SiddhanthKapoor** [soummyaanon/-noteX#3]
![Screenshot from 2024-10-01 01-05-53](https://github.com/user-attachments/assets/1cc9a915-1579-43f4-9f73-ff3b1e67eac6)

"Experience the future of note-taking with AI-powered insights and the noteX Assistance Bot." is not visible in light theme !  I would like to fix some of the light theme issues

However this is a great project...Big ups to you !

**Comment by Anushlinux** [comment]
Hey @soummyaanon it seem that the neutral color palette has not been done correctly for light theme, I would like to work on this #3 issue pls assign it to me

**Comment by soummyaanon** [comment]
> Hey @soummyaanon it seem that the neutral color palette has not been done correctly for light theme, I would like to work on this #3 issue pls assign it to me

sure Just fork this project And after fixing those issue raise a pull request will accept it

**Comment by soummyaanon** [comment]
> ![Screenshot from 2024-10-01 01-05-53](https://private-user-images.githubusercontent.com/177930064/372221787-1cc9a915-1579-43f4-9f73-ff3b1e67eac6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3NTMzNjksIm5iZiI6MTcyNzc1MzA2OSwicGF0aCI6Ii8xNzc5MzAwNjQvMzcyMjIxNzg3LTFjYzlhOTE1LTE1NzktNDNmNC05ZjczLWZmM2IxZTY3ZWFjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQwMzI0MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYjYzNDIzMzllYWMwYTZkYzExZDEyOGJmY2Q1NTgyMjQxMzFkZGE4YWY1MDEzMTM0NjAxNjExNDJmYmMzZGRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.UVIw1ADX7ugyh27up6rDdBQ2T28JsdwlYBw6agJQrjU)
> 
> "Experience the future of note-taking with AI-powered insights and the noteX Assistance Bot." is not visible in light theme ! I would like to fix some of the light theme issues
> 
> However this is a great project...Big ups to you !

THank you so much @SiddhanthKapoor Will fix it soon

**Comment by Anushlinux** [comment]
> > Hey @soummyaanon it seem that the neutral color palette has not been done correctly for light theme, I would like to work on this #3 issue pls assign it to me
> 
> sure Just fork this project And after fixing those issue raise a pull request will accept it 

Is the issue fixed cuz it's closed?

**Comment by soummyaanon** [comment]
No no, the issue  is still there  if you want to join  as a contributor I can add you

**Comment by soummyaanon** [comment]
It seem like i have fixed the issue thank you so much for your valuable  reviews 


![Screenshot 2024-10-01 at 10 59 11 AM](https://github.com/user-attachments/assets/8b658c7a-7314-4761-bf8b-56a45ddc3ca6)
